ibw_jobeet_homepage:
    pattern:  /
    defaults: { _controller: IbwJobeetBundle:Job:index }
IbwJobeetBundle_job:
    resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job
IbwJobeetBundle_category:
    resource: "@IbwJobeetBundle/Resources/config/routing/category.yml"
    prefix:   /category
login:
    pattern:   /login
    defaults:  { _controller: IbwJobeetBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout